{
 "title": "Minecraft Users",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "username", "query": "minecraft_user_info" }
  ]
 },
 "panels": [
  {
   "title": "$username",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "repeat": "username",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "_",
     "crit": 100,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "1 - sum by (username) (minecraft_user_info{username=\"$username\"})",
     "legendFormat": "_",
     "units": "short",
     "valueDisplayRegex": "/.*/",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "repeat": "username",
   "targets": [
    {
     "expr": "avg by (username) (minecraft_health_gauge{username=\"$username\"})"
    }
   ]
  },
  {
   "title": "Xp Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "repeat": "username",
   "targets": [
    {
     "expr": "avg by (usernmae) (minecraft_xp_level_gauge{username=\"$username\"})"
    }
   ]
  },
  {
   "title": "Position",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "repeat": "username",
   "targets": [
    {
     "expr": "avg by (username) (minecraft_pos_x_gauge{username=\"$username\"})",
     "legendFormat": "X"
    },
    {
     "expr": "avg by (username) (minecraft_pos_y_gauge{username=\"$username\"})",
     "legendFormat": "Y"
    },
    {
     "expr": "avg by (username) (minecraft_pos_z_gauge{username=\"$username\"})",
     "legendFormat": "Z"
    }
   ]
  }
 ]
}