name: build

on:
  push:
    branches:
    - 'master'
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get IMAGE_NAME (branch or tag name)
        id: get-imagename
        run: |
          IMAGE_NAME=$(echo "${{ github.ref }}" | sed -e 's|.*/\(.*\)|\1|')
          [[ -n "${{ github.head_ref }}" ]] && IMAGE_NAME=${{ github.head_ref }}

          [[ "${{ github.ref }}" == "refs/tags/"* ]] && IS_TAG="true"

          echo "::set-output name=IMAGE_NAME::${IMAGE_NAME}"
          echo "::set-output name=IS_TAG::${IS_TAG}"

      - name: Build and push (branch)
        uses: docker/build-push-action@v2
        if: ${{ steps.get-imagename.outputs.IS_TAG != 'true' }}
        with:
          push: true
          tags: kanatakita/minecraft-bot:latest,kanatakita/minecraft-bot:${{ steps.get-imagename.outputs.IMAGE_NAME }}-${{ github.sha }}

      - name: Build and push (tag)
        uses: docker/build-push-action@v2
        if: ${{ steps.get-imagename.outputs.IS_TAG == 'true' }}
        with:
          push: true
          tags: kanatakita/minecraft-bot:latest,kanatakita/minecraft-bot:${{ steps.get-imagename.outputs.IMAGE_NAME }}
